### PR TITLE
Add Low Battery Notifier

### PR DESCRIPTION
**Pull request by flyingcakes85**
- Added script
- Added autostart entry in .config/qtile/autostart.sh
- Make script executable in setup.sh

<hr>

Will need to increment `pkgrel` and create PR to PKGBUILD after merging current PR

https://github.com/endeavouros-team/PKGBUILDS/blob/master/eos-skel-ce-qtile/PKGBUILD#L6

### CODE REVIEW

**Comment by flyingcakes85** [comment]
Converted to draft for now. There's a bug fix to do. Don't merge right now.

**Comment by codic12** [comment]
Sure, tell me when it's ready to merge and thanks!

**Comment by flyingcakes85** [comment]
@codic12 

This can be tested and merged now.

To test, you'll need a system with battery (most certainly a laptop).

You'll also need to make following changes to a local copy of script for easy testing

- https://github.com/EndeavourOS-Community-Editions/qtile/pull/1/files#diff-1c31fff3ea86c4efe331d1581ebf15af0d1e533b135d8a3c8eb4e69c78b91243R5 Decrease polling interval to 3 seconds (or anything low) so that you get quick notifications and don't have to wait a minute for next notification
- https://github.com/EndeavourOS-Community-Editions/qtile/pull/1/files#diff-1c31fff3ea86c4efe331d1581ebf15af0d1e533b135d8a3c8eb4e69c78b91243R6 Increase low battery threshold to 101, so that you get notification every time

Then manually run the script from a terminal. You should get notification when your laptop is NOT plugged in an AC source. And you should NOT get notification when laptop is plugged in.

**Comment by codic12** [comment]
I tested it on a real install of qtile I have lying around (on Void) and it works excellently (and is actually pretty useful with default polling interval, but of course not with 3 second ;)), so I'm merging. Thanks!

By the way, the technically correct way to do this is not to poll but to use the Linux kernel's inotify API (https://man7.org/linux/man-pages/man7/inotify.7.html). It's a bit tricky to do with bash, but I can try to figure it out and rewrite the script using it later. That would help it be much more memory and CPU efficient, and you would always instantly get notifications, providing a superior UI.

**Pull request merged**
