### PR TITLE
Same old pull, but with less commits.

### PR DESCRIPTION
**Pull request by emanuelep57**

### CODE REVIEW

**Comment by flyingcakes85** [comment]
This is _much_ cleaner!

There are `__pycache__` folders committed, which shouldn't be included. Like the one at `.config/qtile/__pycache__/config.cpython-39.pyc`

They'll need to be removed.

**Comment by codic12** [comment]
Yeah, I've also added a gitignore for python's compiled class files.

**Comment by flyingcakes85** [comment]
@emanuelep57 

Adding the gitignore doesn't remove already added files. Please manually delete the pycache folders from this branch and add a commit. 

Then @codic12 can squash and merge.

Thanks

**Comment by emanuelep57** [comment]
> @emanuelep57
> 
> Adding the gitignore doesn't remove already added files. Please manually delete the pycache folders from this branch and add a commit.
> 
> Then @codic12 can squash and merge.
> 
> Thanks

So sorry, I forgot to do that by default... It's done now

**Comment by codic12** [comment]
Thanks, will test and merge soon!

**Comment by flyingcakes85** [comment]
Thanks @emanuelep57 !

I'm on a phone, so not sure, but could you please confirm that `.config/qtile/modules/__pycache__` is also deleted?

**Comment by emanuelep57** [comment]
Now it is 😅😅 thanks

**Comment by flyingcakes85** [comment]
Should be good now for squash and merge. Thanks for your contributions!

**Comment by codic12** [comment]
I tested it, and while I appreciate the work, I think I prefer the current style. Sorry, but thanks! I think I'll copy some of the module styles from here to the current style.

**Comment by emanuelep57** [comment]
No problem!

**Pull request closed without merging**
