### PR TITLE
Added "./" to run the script

### PR DESCRIPTION
**Pull request by emanuelep57**
I had forgotten to launch the script with ./

### CODE REVIEW

**Comment by codic12** [comment]
Already fixed.

**Comment by emanuelep57** [comment]
How did you fix?

**Comment by emanuelep57** [comment]
Sorry I am making a huge confusion among all these emails haha

**Comment by codic12** [comment]
Oh, actually I see you were talking about another script, sorry. thanks! but I can't merge this PR because you deleted it

**Comment by codic12** [comment]
You can use the GIthub interface instead

**Pull request closed without merging**
