### PR TITLE
Definitive edition (?)

### PR DESCRIPTION
**Pull request by emanuelep57**
I did major changes, configured xfce4 terminal, rofi menus, bar look, picom, dunst. Everything should be ready like this. Altough I would like to test this in a virtual machine, this is how it looks : 
2021-11-20-144205_1920x1080_scrot

### CODE REVIEW

**Comment by flyingcakes85** [comment]
@codic12 

There seem to be some unneeded files committed (mistakenly?). The "troublesome" ones i.e. that we shouldn't have were added by this commit : https://github.com/EndeavourOS-Community-Editions/qtile/pull/9/commits/6ebc6512e2695cd96cba85d7b8b4a5f612a19cfd

Even though they have been deleted in future commits, the files themselves will be preserved in repository history (and we have no reason to have them).

Suggested squashing then merging if you go ahead.

**Comment by codic12** [comment]
This looks like the culmination of a lot of work, thanks! Just can you change the font back to the previous one? Also would like to try powerline with this, but I'll do that; you basically reworked the whole bar!

**Comment by emanuelep57** [comment]
What font do you mean? The system one?

**Comment by codic12** [comment]
I mean the one that was used previously for the bar and terminal.

**Pull request closed without merging**
