### PR TITLE
EOS logo added, when clicked it will show rofi menu 

### PR DESCRIPTION
**Pull request by emanuelep57**
For me the workspaces with highlight method work fine, I'll check on that later

### CODE REVIEW

**Comment by emanuelep57** [comment]
Ok so I added some "few" things. I added a new script for the battery (because the other one once it was stopped couldn't work again until user restarted xorg, now with this other script it's fixed). I deleted an useless function in the other script "low_bat_notifier", I added battery and volume widgets (but please fix the look with "" because I don't know how to use this character). I added keybindings to cycle trough workspaces and to raise lower or mute volume. Also I fixed a little bug there was in the logo :)

**Comment by emanuelep57** [comment]
Added dunstrc configuration for better looking notifications

**Comment by codic12** [comment]
This is amazing work, I'll merge and polish / tidy up the look.
Thank you very much!

**Comment by codic12** [comment]
I fixed most of the stuff but the battery icon shows erorr on system without battery. Trying to fix...

**Comment by codic12** [comment]
For now just commenting

**Comment by emanuelep57** [comment]
You have to install font awesome 5 to make it work

**Comment by emanuelep57** [comment]
Also excuse me I forgot about this, when it gives an error like crashing
widget or stuff, there is a problem with a dependency 100%. The error will
be reported at the end of the file "~/.local/share/qtile/qtile.log from
there you can see what dependency is missing and add that to the package
list

**Comment by codic12** [comment]
It's actually using Nerd Fonts which includes Font Awesome.
Issue here is not at all missing dependency, the issue is that the battery widget reads from some directory to get the battery status. Problem is if system has no battery it displays some ugly message which breaks the bar layout instead of just hiding the widget.

**Comment by emanuelep57** [comment]
I just fixed it, don't worry, but I found a bug into the battery script so
I'll make a pull request for both in the same moment

**Comment by codic12** [comment]
Sure, base it off master branch because I fixed the things there and remember to uncomment Battery widget.

**Comment by emanuelep57** [comment]
Actually my solution is this :
In the setup file I check if the device has a battery. Now I created 2
config files for qtile one "config_laptop.py" and one "config_desktop.py".
After I see if the device is a laptop or a desktop I delete the useless
file, rename the file in config.py and copy the directory. What do you
think?

**Comment by codic12** [comment]
I don't really like it, I think it is too error-prone. if it is the only way... but I think I know another way .Don't add the battery widget, after you create the list of widgets, try appending the battery widget at the index it has to be only if there is a battery

**Comment by emanuelep57** [comment]
Okay I just did it in the simplest way possible. We check if the machine
has a battery, if it doesn't, I comment out the line of the widget.Battery
with "sed"

**Comment by codic12** [comment]
How do you do that at runtime??

**Comment by emanuelep57** [comment]
Simply in the setup file, after we copy the qtile directory in ~/.config I
added the function to check if the device has a battery, if it doesn't it
will comment out the widget thanks to the bash command "sed"

**Comment by codic12** [comment]
Oh, so not at runtime. Sure!

**Pull request merged**
